app:
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db:postgres
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: password
    USERNAME: app
    PASSWORD: password
  privileged: true

db:
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - notebook_data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: password
  privileged: true
